apiVersion: v2
appVersion: 'ml-api-adapter: v14.0.0; central-ledger: v16.3.1; account-lookup-service:
  v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; central-event-processor:
  v12.0.0; bulk-api-adapter: v14.2.0; email-notifier: v12.0.0; als-oracle-pathfinder:
  v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator:
  v13.0.1; sdk-scheme-adapter: v21.4.0; thirdparty-sdk: v15.1.0; ml-testing-toolkit:
  v15.2.0; ml-testing-toolkit-ui: v15.0.1;'
dependencies:
- condition: central.enabled
  name: central
  repository: file://../central
  version: 14.1.0
- condition: ml-api-adapter.enabled
  name: ml-api-adapter
  repository: file://../ml-api-adapter
  version: 12.1.0
- condition: account-lookup-service.enabled
  name: account-lookup-service
  repository: file://../account-lookup-service
  version: 13.1.0
- condition: quoting-service.enabled
  name: quoting-service
  repository: file://../quoting-service
  version: 13.1.0
- condition: simulator.enabled
  name: simulator
  repository: file://../simulator
  version: 12.1.0
- condition: mojaloop-simulator.enabled
  name: mojaloop-simulator
  repository: file://../mojaloop-simulator
  version: 14.1.0
- condition: mojaloop-bulk.enabled
  name: mojaloop-bulk
  repository: file://../mojaloop-bulk
  version: 14.1.0
- condition: transaction-requests-service.enabled
  name: transaction-requests-service
  repository: file://../transaction-requests-service
  version: 12.1.0
- condition: emailnotifier.enabled
  name: emailnotifier
  repository: file://../emailnotifier
  version: 12.1.0
- condition: ml-testing-toolkit.enabled
  name: ml-testing-toolkit
  repository: file://../ml-testing-toolkit
  version: 15.3.0
- alias: ml-ttk-test-setup
  condition: ml-ttk-test-setup.tests.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-test-val-gp
  condition: ml-ttk-test-val-gp.tests.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-test-val-bulk
  condition: ml-ttk-test-val-bulk.tests.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-test-setup-tp
  condition: ml-ttk-test-setup-tp.tests.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-test-val-tp
  condition: ml-ttk-test-val-tp.tests.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-posthook-setup
  condition: ml-ttk-posthook-setup.postInstallHook.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-posthook-tests
  condition: ml-ttk-posthook-tests.postInstallHook.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-cronjob-tests
  condition: ml-ttk-cronjob-tests.scheduling.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- condition: thirdparty.enabled
  name: thirdparty
  repository: file://../thirdparty
  version: 2.1.0
- condition: mojaloop-ttk-simulators.enabled
  name: mojaloop-ttk-simulators
  repository: file://../mojaloop-ttk-simulators
  version: 1.0.0
- alias: ml-ttk-test-setup-sdk-bulk
  condition: ml-ttk-test-setup-sdk-bulk.tests.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- alias: ml-ttk-test-val-sdk-bulk
  condition: ml-ttk-test-val-sdk-bulk.tests.enabled
  name: ml-testing-toolkit-cli
  repository: file://../ml-testing-toolkit-cli
  version: 15.1.0
- name: common
  repository: https://docs.mojaloop.io/charts/repo
  tags:
  - moja-common
  version: 2.0.0
description: Mojaloop Helm chart for Kubernetes
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
maintainers:
- email: miguel.debarros@modusbox.com
  name: Miguel de Barros
- email: tomd@crosslaketech.com
  name: Tom Daly
name: mojaloop
sources:
- https://github.com/mojaloop/mojaloop
- https://github.com/mojaloop/helm
version: 14.1.0
